#!/bin/bash

set -e
#set -x

if [ $# -ne 1 ]
then
  echo "Usage: `basename $0` test_dir"
  exit -1
fi

# cd to testdir
testDir=$1
cd $testDir

# convert txt files to binary
hsssStrainTextFileToBinary 0 < $PROJECT_HOME/ApiCommonWebService/HighSpeedSnpSearch/test/strain1.txt > 1
hsssStrainTextFileToBinary 0 < $PROJECT_HOME/ApiCommonWebService/HighSpeedSnpSearch/test/strain2.txt > 2
hsssStrainTextFileToBinary 0 < $PROJECT_HOME/ApiCommonWebService/HighSpeedSnpSearch/test/strain3.txt > 3
hsssStrainTextFileToBinary 0 < $PROJECT_HOME/ApiCommonWebService/HighSpeedSnpSearch/test/strain4.txt > 4
hsssStrainTextFileToBinary 0 < $PROJECT_HOME/ApiCommonWebService/HighSpeedSnpSearch/test/referenceGenome.txt > referenceGenome.dat

# merge two files, convert back to text and compare with expected
hsssMergeStrains 1 1 2 2 > mergeStrains_test.out
hsssDumpStrains 0 < mergeStrains_test.out > mergeStrains_test.txt

diff mergeStrains_test.txt  $PROJECT_HOME/ApiCommonWebService/HighSpeedSnpSearch/test/mergeStrains_answer.txt
diffStat=$?
if [ $diffStat != 0 ]; then
   exit -1
fi

# generate findPolymorphism script
echo -e "1\n2\n3\n4" | hsssGeneratePolymorphismScript $testDir $testDir 1 1 > runPolymorphismSearch
chmod +x runPolymorphismSearch

# run that script and compare output with expected.
./runPolymorphismSearch > polymorphismSearch_result.txt

diff polymorphismSearch_result.txt  $PROJECT_HOME/ApiCommonWebService/HighSpeedSnpSearch/test/polymorphismSearch_expected.txt
diffStat=$?
if [ $diffStat != 0 ]; then
   exit -1
fi
